if ! pgrep -x Hyprland > /dev/null; then
    # this is for a easier login without a display manager:
    #
    # ls /etc/systemd/system/getty.target.wants/
    # EDITOR=nvim sudo -E systemctl edit getty@tty1
    #
    # paste:
    # [Service]
    # ExecStart=
    # ExecStart=-/sbin/agetty --autologin aleks-tacconi --noclear %I $TERM
    #
    #
    # sudo systemctl daemon-reexec                   
    # sudo systemctl restart getty@tty1
    #
    Hyprland
fi

zstyle :compinstall filename '/home/aleks-tacconi/.zshrc'
autoload -Uz compinit
compinit


eval "$(zoxide init zsh)"


ZSH_THEME=robbyrussell
export ZSH="/usr/share/oh-my-zsh"
source $ZSH/oh-my-zsh.sh


alias ".."="cd .."
alias "v"="nvim"
alias "ls"="eza --group-directories-first --git"
alias "ll"="ls -lah"
alias "cat"="bat"
alias "cd"="z"
alias "y"="yazi"


if [[ ! -f ~/.zplug/init.zsh ]]; then
  git clone https://github.com/zplug/zplug ~/.zplug
fi

source ~/.zplug/init.zsh

zplug "zsh-users/zsh-syntax-highlighting"
zplug "zsh-users/zsh-autosuggestions"

if ! zplug check --verbose; then
    zplug install
fi

zplug load


HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory
source <(fzf --zsh)


export PATH=$PATH:/home/aleks-tacconi/.cargo/bin
