zstyle :compinstall filename '/home/aleks-tacconi/.zshrc'
autoload -Uz compinit
compinit


eval "$(zoxide init zsh)"


ZSH_THEME=robbyrussell
export ZSH="/usr/share/oh-my-zsh"
source $ZSH/oh-my-zsh.sh


alias ".."="cd .."
alias "v"="nvim"
alias "ls"="eza --group-directories-first --git"
alias "ll"="ls -lah"
alias "cat"="bat"
alias "cd"="z"
alias "y"="yazi"


if [[ ! -f ~/.zplug/init.zsh ]]; then
  git clone https://github.com/zplug/zplug ~/.zplug
fi

source ~/.zplug/init.zsh

zplug "zsh-users/zsh-syntax-highlighting"
zplug "zsh-users/zsh-autosuggestions"

if ! zplug check --verbose; then
    zplug install
fi

zplug load


HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory
source <(fzf --zsh)


export PATH=$PATH:/home/aleks-tacconi/.cargo/bin
